version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@mapbox/docs"
    allow:
      - dependency-name: "prettier"
      - dependency-name: "husky"
      - dependency-name: "lint-staged"